# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hotels in Las Vegas
author: Yingrui, Sebastian, Hanlu 
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  
## use thebe for showing ipywidgets interactive plots 
launch_buttons:
  thebe                  : true
  
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://hanlululu.github.io/Socialgraphswebsite.io/Page4_Sentiment.html?fbclid=IwAR0h0zjmyFPv81icsAOa24Tff27JMEx0SETuggSlFd0ewjuGJE3VIBSg3pk  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js